name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set $VERSION variable
        id: version
        run: |
          echo ::set-output name=VERSION::$(echo $(GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} gh release list --repo $GITHUB_REPOSITORY | cut -f 1 | head -n 1))

      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
        run: |
          chmod +x gradlew
          ./gradlew -Pversion=$VERSION build

#      - uses: actions/upload-artifact@v2
#        with:
#          name: Package
#          path: build/libs
